"use client";

import { createContext, useContext, useState, useCallback, useEffect } from "react";

export type Locale = "en" | "zh-CN" | "zh-TW" | "es" | "ar";

export const LOCALE_NAMES: Record<Locale, string> = {
  en: "English",
  "zh-CN": "简体中文",
  "zh-TW": "繁體中文",
  es: "Español",
  ar: "العربية",
};

export const LOCALES = Object.keys(LOCALE_NAMES) as Locale[];

interface Translations {
  siteTitle: string; siteDescription: string; brand: string;
  signIn: string; signOut: string;
  heroTitle1: string; heroTitle2: string; heroSubtitle: string; heroCta: string;
  featureSmartTitle: string; featureSmartDesc: string;
  featureLowAiTitle: string; featureLowAiDesc: string;
  featureFastTitle: string; featureFastDesc: string;
  editorTitle: string; editorSubtitle: string;
  todayRemaining: string; rewriting: string; startRewrite: string;
  modeLight: string; modeLightDesc: string;
  modeMedium: string; modeMediumDesc: string;
  modeDeep: string; modeDeepDesc: string;
  originalText: string; words: string; paste: string; clear: string;
  editorPlaceholder: string; rewriteResult: string; copy: string;
  loadingPlaceholder: string; resultPlaceholder: string; aiRewriting: string;
  toastNoText: string; toastTooLong: string; toastTooShort: string;
  toastFailed: string; toastSuccess: string; toastNetworkError: string;
  loginTitle: string; loginDesc: string; loginGoogle: string; loginTerms: string;
  loading: string;
  aiDetect: string; detecting: string;
  estimatedAiRate: string; aiRateLabel: string;
  vocabulary: string; structure: string; flow: string; voice: string;
  aiRatePass: string; aiRateWarning: string; aiRateFail: string;
  dashboard: string; dashboardTitle: string; dashboardSubtitle: string;
  todayUsage: string; lastResult: string;
  noResultYet: string; noResultDesc: string; goRewrite: string;
  overallAiRate: string; detailBreakdown: string;
  // Sidebar nav
  navTools: string; navAiRewrite: string; navAiDetect: string;
  navAccount: string; navProfile: string; navPlans: string;
  // Detection page
  detectTitle: string; detectSubtitle: string;
  detectPlaceholder: string; detectButton: string; detectResult: string;
  // Profile page
  profileTitle: string; profileSubtitle: string;
  accountName: string; accountEmail: string; accountPlan: string;
  planFree: string; planPro: string;
  // Plans page
  plansTitle: string; plansSubtitle: string;
  planFreeTitle: string; planFreeDesc: string;
  planDayTitle: string; planDayDesc: string; planDayPrice: string;
  planWeekTitle: string; planWeekDesc: string; planWeekPrice: string;
  planProTitle: string; planProDesc: string;
  planFreePrice: string; planProPrice: string;
  planCurrent: string; planUpgrade: string; planContactUs: string;
  usesPerDay: string; wordsPerUse: string; perDay: string; perWeek: string; perMonth: string;
  // Share & Support
  navShareSupport: string; navShare: string; navFeedback: string;
  shareTitle: string; shareSubtitle: string;
  shareLink: string; shareLinkDesc: string;
  shareQrCode: string; shareCopied: string; shareCopyLink: string;
  shareBonus: string; shareBonusDesc: string;
  feedbackTitle: string; feedbackSubtitle: string;
  feedbackPlaceholder: string; feedbackSubmit: string; feedbackSubmitting: string;
  feedbackSuccess: string; feedbackError: string; feedbackCharCount: string;
  // Business
  navBusiness: string; navCooperation: string;
  cooperationTitle: string; cooperationSubtitle: string;
  cooperationEmail: string; cooperationDesc: string;
  // Turnitin disclaimer
  turnitinDisclaimer: string;
}

const en: Translations = {
  siteTitle: "HumanizeAI - AI Text Humanizer",
  siteDescription: "Transform AI-generated essays into natural human writing style, effectively reducing Turnitin AI detection rate",
  brand: "HumanizeAI",
  signIn: "Sign In", signOut: "Sign Out",
  heroTitle1: "Make AI Text", heroTitle2: " Human Again ",
  heroSubtitle: "Transform essays generated by ChatGPT, DeepSeek and other AI tools into natural, fluent human writing style. Effectively reduce Turnitin AI detection rate below 19%.",
  heroCta: "Get Started Free",
  featureSmartTitle: "Smart Rewriting", featureSmartDesc: "Powered by GPT-4o with three rewriting intensities, precisely preserving academic meaning",
  featureLowAiTitle: "Low AI Detection", featureLowAiDesc: "Optimized for Turnitin — deep rewrite mode can achieve below 19% AI rate",
  featureFastTitle: "Fast & Easy", featureFastDesc: "Paste text and rewrite with one click, free uses every day",
  editorTitle: "Text Rewrite", editorSubtitle: "Paste AI-generated text, choose rewriting intensity, get humanized results in one click",
  todayRemaining: "Remaining today:", rewriting: "Rewriting...", startRewrite: "Start Rewrite",
  modeLight: "Light Rewrite", modeLightDesc: "Minimal changes, replace AI-typical vocabulary",
  modeMedium: "Medium Rewrite", modeMediumDesc: "Restructure sentences, adjust expressions",
  modeDeep: "Deep Rewrite", modeDeepDesc: "Complete rewrite, preserve original meaning",
  originalText: "Original Text", words: "words", paste: "Paste", clear: "Clear",
  editorPlaceholder: "Paste AI-generated essay text here...\n\nSupports text from ChatGPT, DeepSeek, Claude and other AI tools.\nRecommended: no more than 2,000 words per submission.",
  rewriteResult: "Rewrite Result", copy: "Copy",
  loadingPlaceholder: "Rewriting in progress, please wait...",
  resultPlaceholder: "Rewritten text will appear here...",
  aiRewriting: "AI is rewriting your text...",
  toastNoText: "Please enter text to rewrite first",
  toastTooLong: "Text exceeds 2,000 word limit, please split and submit",
  toastTooShort: "Text too short, please enter at least 10 words",
  toastFailed: "Rewrite failed", toastSuccess: "Rewrite complete!",
  toastNetworkError: "Network error, please try again later",
  loginTitle: "Sign in to HumanizeAI",
  loginDesc: "Sign in with your Google account to start using AI text rewriting",
  loginGoogle: "Sign in with Google",
  loginTerms: "By signing in, you agree to our Terms of Service and Privacy Policy",
  loading: "Loading...",
  aiDetect: "AI Detection", detecting: "Detecting...",
  estimatedAiRate: "Estimated AI Rate", aiRateLabel: "AI Detection Rate",
  vocabulary: "Vocabulary", structure: "Sentence Structure", flow: "Paragraph Flow", voice: "Human Voice",
  aiRatePass: "Pass — Below Turnitin threshold",
  aiRateWarning: "Borderline — Consider deep rewrite",
  aiRateFail: "High risk — Use deep rewrite mode",
  dashboard: "Dashboard", dashboardTitle: "Dashboard",
  dashboardSubtitle: "View your usage and latest rewrite AI detection results",
  todayUsage: "Today's Usage", lastResult: "Latest Rewrite Result",
  noResultYet: "No Result Yet", noResultDesc: "Complete a rewrite to see AI detection analysis here",
  goRewrite: "Go to Rewrite", overallAiRate: "Overall AI Rate", detailBreakdown: "Detail Breakdown",
  navTools: "Tools", navAiRewrite: "AI Rewrite", navAiDetect: "AI Detection",
  navAccount: "Account", navProfile: "Profile", navPlans: "Plans & Pricing",
  detectTitle: "AI Detection", detectSubtitle: "Paste any text to check its AI detection rate",
  detectPlaceholder: "Paste text here to analyze its AI detection rate...\n\nSupports any English academic text.",
  detectButton: "Start Detection", detectResult: "Detection Result",
  profileTitle: "Profile", profileSubtitle: "Manage your account information",
  accountName: "Name", accountEmail: "Email", accountPlan: "Current Plan",
  planFree: "Free", planPro: "Pro",
  plansTitle: "Plans & Pricing", plansSubtitle: "Choose the plan that fits your needs",
  planFreeTitle: "Free", planFreeDesc: "Get started with basic access",
  planDayTitle: "Day Pass", planDayDesc: "Full access for 24 hours", planDayPrice: "$0.99",
  planWeekTitle: "Week Pass", planWeekDesc: "Full access for 7 days", planWeekPrice: "$3.99",
  planProTitle: "Pro", planProDesc: "Unlock full power for academic writing",
  planFreePrice: "$0", planProPrice: "$14.99",
  planCurrent: "Current Plan", planUpgrade: "Upgrade", planContactUs: "Buy Now",
  usesPerDay: "uses / day", wordsPerUse: "words / use", perDay: "/ day", perWeek: "/ week", perMonth: "/ month",
  navShareSupport: "Share & Support", navShare: "Share", navFeedback: "Feedback",
  shareTitle: "Share & Earn", shareSubtitle: "Share your referral link with friends. When they sign up, you get +3 bonus uses!",
  shareLink: "Your Referral Link", shareLinkDesc: "Share this link with friends to earn bonus uses",
  shareQrCode: "QR Code", shareCopied: "Copied!", shareCopyLink: "Copy Link",
  shareBonus: "Referral Bonus", shareBonusDesc: "You will earn +3 free uses when a new user signs up with your link (one-time bonus)",
  feedbackTitle: "Feedback", feedbackSubtitle: "Help us improve! Share your thoughts or suggestions (max 100 characters)",
  feedbackPlaceholder: "Tell us what you think...", feedbackSubmit: "Submit Feedback", feedbackSubmitting: "Submitting...",
  feedbackSuccess: "Thank you for your feedback!", feedbackError: "Failed to submit, please try again", feedbackCharCount: "characters",
  navBusiness: "Business", navCooperation: "Cooperation",
  cooperationTitle: "Business Cooperation", cooperationSubtitle: "Interested in partnering with us? Get in touch!",
  cooperationEmail: "Contact Email", cooperationDesc: "For business inquiries, partnerships, or collaboration opportunities, please reach out to us via email.",
  turnitinDisclaimer: "This is an estimated score. For official results, please use Turnitin directly.",
};

const zhCN: Translations = {
  siteTitle: "HumanizeAI - AI 文本人性化改写", siteDescription: "将 AI 生成的论文文本转化为自然的人类写作风格，有效降低 Turnitin AI 检测率",
  brand: "HumanizeAI", signIn: "登录", signOut: "退出登录",
  heroTitle1: "让 AI 文本", heroTitle2: " 回归人性 ",
  heroSubtitle: "将 ChatGPT、DeepSeek 等 AI 生成的论文文本，智能改写为自然流畅的人类写作风格。有效降低 Turnitin AI 检测率至 19% 以下。",
  heroCta: "免费开始使用",
  featureSmartTitle: "智能改写", featureSmartDesc: "基于 GPT-4o，三种改写强度可选，精准保留学术含义",
  featureLowAiTitle: "低 AI 检测率", featureLowAiDesc: "针对 Turnitin 优化，深度改写模式 AI 率可低于 19%",
  featureFastTitle: "快速便捷", featureFastDesc: "粘贴文本一键改写，每日免费使用额度",
  editorTitle: "文本改写", editorSubtitle: "粘贴 AI 生成的文本，选择改写强度，一键获得人性化结果",
  todayRemaining: "今日剩余:", rewriting: "改写中...", startRewrite: "开始改写",
  modeLight: "轻度改写", modeLightDesc: "最小改动，替换 AI 高频词汇",
  modeMedium: "中度改写", modeMediumDesc: "重构句式，调整表达方式",
  modeDeep: "深度改写", modeDeepDesc: "完全重写，保持原意不变",
  originalText: "原始文本", words: "词", paste: "粘贴", clear: "清空",
  editorPlaceholder: "在此粘贴 AI 生成的论文文本...\n\n支持 ChatGPT、DeepSeek、Claude 等 AI 生成的英文学术文本。\n建议每次提交不超过 2000 词。",
  rewriteResult: "改写结果", copy: "复制",
  loadingPlaceholder: "正在改写中，请稍候...", resultPlaceholder: "改写后的文本将显示在此处...",
  aiRewriting: "AI 正在改写文本...",
  toastNoText: "请先输入需要改写的文本", toastTooLong: "文本超过 2000 词限制，请分段提交",
  toastTooShort: "文本太短，请至少输入 10 个词",
  toastFailed: "改写失败", toastSuccess: "改写完成！", toastNetworkError: "网络错误，请稍后重试",
  loginTitle: "登录 HumanizeAI", loginDesc: "使用 Google 账号登录，即可开始使用 AI 文本改写服务",
  loginGoogle: "使用 Google 登录", loginTerms: "登录即表示您同意我们的服务条款和隐私政策",
  loading: "加载中...",
  aiDetect: "AI 检测", detecting: "检测中...",
  estimatedAiRate: "预估 AI 率", aiRateLabel: "AI 检测率",
  vocabulary: "词汇选择", structure: "句式结构", flow: "段落衔接", voice: "人类语感",
  aiRatePass: "通过 — 低于 Turnitin 阈值", aiRateWarning: "边缘 — 建议使用深度改写",
  aiRateFail: "高风险 — 请使用深度改写模式",
  dashboard: "仪表盘", dashboardTitle: "仪表盘", dashboardSubtitle: "查看使用情况和最近改写的 AI 检测结果",
  todayUsage: "今日用量", lastResult: "最近改写结果",
  noResultYet: "暂无结果", noResultDesc: "完成一次改写后，这里将显示 AI 检测分析",
  goRewrite: "去改写", overallAiRate: "综合 AI 率", detailBreakdown: "详细分项",
  navTools: "工具", navAiRewrite: "AI 改写", navAiDetect: "AI 检测",
  navAccount: "账号", navProfile: "个人资料", navPlans: "套餐与定价",
  detectTitle: "AI 检测", detectSubtitle: "粘贴任意文本，检测其 AI 率",
  detectPlaceholder: "在此粘贴文本以分析 AI 检测率...\n\n支持任意英文学术文本。",
  detectButton: "开始检测", detectResult: "检测结果",
  profileTitle: "个人资料", profileSubtitle: "管理您的账号信息",
  accountName: "姓名", accountEmail: "邮箱", accountPlan: "当前套餐",
  planFree: "免费版", planPro: "专业版",
  plansTitle: "套餐与定价", plansSubtitle: "选择适合您的套餐",
  planFreeTitle: "免费版", planFreeDesc: "基础使用，快速上手",
  planDayTitle: "天卡", planDayDesc: "24 小时完整使用权限", planDayPrice: "$0.99",
  planWeekTitle: "周卡", planWeekDesc: "7 天完整使用权限", planWeekPrice: "$3.99",
  planProTitle: "专业版", planProDesc: "解锁全部功能，畅享学术写作",
  planFreePrice: "¥0", planProPrice: "$14.99",
  planCurrent: "当前套餐", planUpgrade: "升级", planContactUs: "立即购买",
  usesPerDay: "次/天", wordsPerUse: "词/次", perDay: "/天", perWeek: "/周", perMonth: "/月",
  navShareSupport: "分享与支持", navShare: "分享", navFeedback: "反馈",
  shareTitle: "分享赚取", shareSubtitle: "分享你的邀请链接给朋友，当他们注册后你将获得 +3 次免费使用额度！",
  shareLink: "你的邀请链接", shareLinkDesc: "分享此链接给朋友，赚取额外使用次数",
  shareQrCode: "二维码", shareCopied: "已复制！", shareCopyLink: "复制链接",
  shareBonus: "邀请奖励", shareBonusDesc: "当新用户通过你的链接注册后，你将获得 +3 次免费使用额度（一次性奖励）",
  feedbackTitle: "反馈", feedbackSubtitle: "帮助我们改进！分享你的想法或建议（最多 100 字）",
  feedbackPlaceholder: "告诉我们你的想法...", feedbackSubmit: "提交反馈", feedbackSubmitting: "提交中...",
  feedbackSuccess: "感谢你的反馈！", feedbackError: "提交失败，请重试", feedbackCharCount: "字",
  navBusiness: "商务", navCooperation: "合作",
  cooperationTitle: "商务合作", cooperationSubtitle: "有合作意向？欢迎联系我们！",
  cooperationEmail: "联系邮箱", cooperationDesc: "如有商务咨询、合作伙伴关系或协作机会，请通过邮件联系我们。",
  turnitinDisclaimer: "此为估算分数，最终结果请以 Turnitin 官方检测为准。",
};

const zhTW: Translations = {
  siteTitle: "HumanizeAI - AI 文本人性化改寫", siteDescription: "將 AI 生成的論文文本轉化為自然的人類寫作風格，有效降低 Turnitin AI 偵測率",
  brand: "HumanizeAI", signIn: "登入", signOut: "登出",
  heroTitle1: "讓 AI 文本", heroTitle2: " 回歸人性 ",
  heroSubtitle: "將 ChatGPT、DeepSeek 等 AI 生成的論文文本，智慧改寫為自然流暢的人類寫作風格。有效降低 Turnitin AI 偵測率至 19% 以下。",
  heroCta: "免費開始使用",
  featureSmartTitle: "智慧改寫", featureSmartDesc: "基於 GPT-4o，三種改寫強度可選，精準保留學術含義",
  featureLowAiTitle: "低 AI 偵測率", featureLowAiDesc: "針對 Turnitin 最佳化，深度改寫模式 AI 率可低於 19%",
  featureFastTitle: "快速便捷", featureFastDesc: "貼上文本一鍵改寫，每日免費使用額度",
  editorTitle: "文本改寫", editorSubtitle: "貼上 AI 生成的文本，選擇改寫強度，一鍵獲得人性化結果",
  todayRemaining: "今日剩餘:", rewriting: "改寫中...", startRewrite: "開始改寫",
  modeLight: "輕度改寫", modeLightDesc: "最小改動，替換 AI 高頻詞彙",
  modeMedium: "中度改寫", modeMediumDesc: "重構句式，調整表達方式",
  modeDeep: "深度改寫", modeDeepDesc: "完全重寫，保持原意不變",
  originalText: "原始文本", words: "詞", paste: "貼上", clear: "清空",
  editorPlaceholder: "在此貼上 AI 生成的論文文本...\n\n支援 ChatGPT、DeepSeek、Claude 等 AI 生成的英文學術文本。\n建議每次提交不超過 2000 詞。",
  rewriteResult: "改寫結果", copy: "複製",
  loadingPlaceholder: "正在改寫中，請稍候...", resultPlaceholder: "改寫後的文本將顯示在此處...",
  aiRewriting: "AI 正在改寫文本...",
  toastNoText: "請先輸入需要改寫的文本", toastTooLong: "文本超過 2000 詞限制，請分段提交",
  toastTooShort: "文本太短，請至少輸入 10 個詞",
  toastFailed: "改寫失敗", toastSuccess: "改寫完成！", toastNetworkError: "網路錯誤，請稍後重試",
  loginTitle: "登入 HumanizeAI", loginDesc: "使用 Google 帳號登入，即可開始使用 AI 文本改寫服務",
  loginGoogle: "使用 Google 登入", loginTerms: "登入即表示您同意我們的服務條款和隱私權政策",
  loading: "載入中...",
  aiDetect: "AI 偵測", detecting: "偵測中...",
  estimatedAiRate: "預估 AI 率", aiRateLabel: "AI 偵測率",
  vocabulary: "詞彙選擇", structure: "句式結構", flow: "段落銜接", voice: "人類語感",
  aiRatePass: "通過 — 低於 Turnitin 閾值", aiRateWarning: "邊緣 — 建議使用深度改寫",
  aiRateFail: "高風險 — 請使用深度改寫模式",
  dashboard: "儀表板", dashboardTitle: "儀表板", dashboardSubtitle: "查看使用情況和最近改寫的 AI 偵測結果",
  todayUsage: "今日用量", lastResult: "最近改寫結果",
  noResultYet: "暫無結果", noResultDesc: "完成一次改寫後，這裡將顯示 AI 偵測分析",
  goRewrite: "去改寫", overallAiRate: "綜合 AI 率", detailBreakdown: "詳細分項",
  navTools: "工具", navAiRewrite: "AI 改寫", navAiDetect: "AI 偵測",
  navAccount: "帳號", navProfile: "個人資料", navPlans: "方案與定價",
  detectTitle: "AI 偵測", detectSubtitle: "貼上任意文本，偵測其 AI 率",
  detectPlaceholder: "在此貼上文本以分析 AI 偵測率...\n\n支援任意英文學術文本。",
  detectButton: "開始偵測", detectResult: "偵測結果",
  profileTitle: "個人資料", profileSubtitle: "管理您的帳號資訊",
  accountName: "姓名", accountEmail: "電子郵件", accountPlan: "目前方案",
  planFree: "免費版", planPro: "專業版",
  plansTitle: "方案與定價", plansSubtitle: "選擇適合您的方案",
  planFreeTitle: "免費版", planFreeDesc: "基礎使用，快速上手",
  planDayTitle: "日卡", planDayDesc: "24 小時完整使用權限", planDayPrice: "$0.99",
  planWeekTitle: "週卡", planWeekDesc: "7 天完整使用權限", planWeekPrice: "$3.99",
  planProTitle: "專業版", planProDesc: "解鎖全部功能，暢享學術寫作",
  planFreePrice: "$0", planProPrice: "$14.99",
  planCurrent: "目前方案", planUpgrade: "升級", planContactUs: "立即購買",
  usesPerDay: "次/天", wordsPerUse: "詞/次", perDay: "/天", perWeek: "/週", perMonth: "/月",
  navShareSupport: "分享與支持", navShare: "分享", navFeedback: "回饋",
  shareTitle: "分享賺取", shareSubtitle: "分享你的邀請連結給朋友，當他們註冊後你將獲得 +3 次免費使用額度！",
  shareLink: "你的邀請連結", shareLinkDesc: "分享此連結給朋友，賺取額外使用次數",
  shareQrCode: "QR Code", shareCopied: "已複製！", shareCopyLink: "複製連結",
  shareBonus: "邀請獎勵", shareBonusDesc: "當新用戶透過你的連結註冊後，你將獲得 +3 次免費使用額度（一次性獎勵）",
  feedbackTitle: "回饋", feedbackSubtitle: "幫助我們改進！分享你的想法或建議（最多 100 字）",
  feedbackPlaceholder: "告訴我們你的想法...", feedbackSubmit: "提交回饋", feedbackSubmitting: "提交中...",
  feedbackSuccess: "感謝你的回饋！", feedbackError: "提交失敗，請重試", feedbackCharCount: "字",
  navBusiness: "商務", navCooperation: "合作",
  cooperationTitle: "商務合作", cooperationSubtitle: "有合作意向？歡迎聯繫我們！",
  cooperationEmail: "聯繫郵箱", cooperationDesc: "如有商務諮詢、合作夥伴關係或協作機會，請透過郵件聯繫我們。",
  turnitinDisclaimer: "此為估算分數，最終結果請以 Turnitin 官方檢測為準。",
};

const es: Translations = {
  siteTitle: "HumanizeAI - Humanizador de Texto AI", siteDescription: "Transforma ensayos generados por IA en estilo de escritura humana natural, reduciendo la tasa de detección de Turnitin",
  brand: "HumanizeAI", signIn: "Iniciar Sesión", signOut: "Cerrar Sesión",
  heroTitle1: "Haz que el Texto AI", heroTitle2: " Sea Humano ",
  heroSubtitle: "Transforma ensayos generados por ChatGPT, DeepSeek y otras herramientas AI en un estilo de escritura humano natural y fluido. Reduce la tasa de detección AI de Turnitin por debajo del 19%.",
  heroCta: "Comenzar Gratis",
  featureSmartTitle: "Reescritura Inteligente", featureSmartDesc: "Impulsado por GPT-4o con tres niveles de intensidad, preservando el significado académico",
  featureLowAiTitle: "Baja Detección AI", featureLowAiDesc: "Optimizado para Turnitin — el modo profundo puede lograr menos del 19%",
  featureFastTitle: "Rápido y Fácil", featureFastDesc: "Pega texto y reescribe con un clic, usos gratuitos diarios",
  editorTitle: "Reescribir Texto", editorSubtitle: "Pega texto generado por AI, elige la intensidad, obtén resultados humanizados con un clic",
  todayRemaining: "Restantes hoy:", rewriting: "Reescribiendo...", startRewrite: "Iniciar Reescritura",
  modeLight: "Ligera", modeLightDesc: "Cambios mínimos, reemplazar vocabulario típico de AI",
  modeMedium: "Media", modeMediumDesc: "Reestructurar oraciones, ajustar expresiones",
  modeDeep: "Profunda", modeDeepDesc: "Reescritura completa, preservar significado original",
  originalText: "Texto Original", words: "palabras", paste: "Pegar", clear: "Limpiar",
  editorPlaceholder: "Pega aquí el texto del ensayo generado por AI...\n\nSoporta texto de ChatGPT, DeepSeek, Claude y otras herramientas AI.\nRecomendado: no más de 2,000 palabras por envío.",
  rewriteResult: "Resultado de Reescritura", copy: "Copiar",
  loadingPlaceholder: "Reescritura en progreso, por favor espera...",
  resultPlaceholder: "El texto reescrito aparecerá aquí...",
  aiRewriting: "AI está reescribiendo tu texto...",
  toastNoText: "Por favor ingresa texto para reescribir primero",
  toastTooLong: "El texto excede el límite de 2,000 palabras",
  toastTooShort: "Texto muy corto, ingresa al menos 10 palabras",
  toastFailed: "Reescritura fallida", toastSuccess: "¡Reescritura completa!",
  toastNetworkError: "Error de red, intenta de nuevo más tarde",
  loginTitle: "Inicia sesión en HumanizeAI", loginDesc: "Inicia sesión con tu cuenta de Google para comenzar a usar la reescritura de texto AI",
  loginGoogle: "Iniciar sesión con Google", loginTerms: "Al iniciar sesión, aceptas nuestros Términos de Servicio y Política de Privacidad",
  loading: "Cargando...",
  aiDetect: "Detección AI", detecting: "Detectando...",
  estimatedAiRate: "Tasa AI Estimada", aiRateLabel: "Tasa de Detección AI",
  vocabulary: "Vocabulario", structure: "Estructura de Oraciones", flow: "Flujo de Párrafos", voice: "Voz Humana",
  aiRatePass: "Aprobado — Por debajo del umbral de Turnitin",
  aiRateWarning: "Límite — Considera reescritura profunda",
  aiRateFail: "Alto riesgo — Usa modo de reescritura profunda",
  dashboard: "Panel", dashboardTitle: "Panel", dashboardSubtitle: "Ve tu uso y los últimos resultados de detección AI",
  todayUsage: "Uso de Hoy", lastResult: "Último Resultado de Reescritura",
  noResultYet: "Sin Resultados Aún", noResultDesc: "Completa una reescritura para ver el análisis de detección AI aquí",
  goRewrite: "Ir a Reescribir", overallAiRate: "Tasa AI General", detailBreakdown: "Desglose Detallado",
  navTools: "Herramientas", navAiRewrite: "Reescritura AI", navAiDetect: "Detección AI",
  navAccount: "Cuenta", navProfile: "Perfil", navPlans: "Planes y Precios",
  detectTitle: "Detección AI", detectSubtitle: "Pega cualquier texto para verificar su tasa de detección AI",
  detectPlaceholder: "Pega texto aquí para analizar la tasa de detección AI...\n\nSoporta cualquier texto académico en inglés.",
  detectButton: "Iniciar Detección", detectResult: "Resultado de Detección",
  profileTitle: "Perfil", profileSubtitle: "Administra la información de tu cuenta",
  accountName: "Nombre", accountEmail: "Email", accountPlan: "Plan Actual",
  planFree: "Gratis", planPro: "Pro",
  plansTitle: "Planes y Precios", plansSubtitle: "Elige el plan que se ajuste a tus necesidades",
  planFreeTitle: "Gratis", planFreeDesc: "Comienza con acceso básico",
  planDayTitle: "Pase Diario", planDayDesc: "Acceso completo por 24 horas", planDayPrice: "$0.99",
  planWeekTitle: "Pase Semanal", planWeekDesc: "Acceso completo por 7 días", planWeekPrice: "$3.99",
  planProTitle: "Pro", planProDesc: "Desbloquea todo el poder para escritura académica",
  planFreePrice: "$0", planProPrice: "$14.99",
  planCurrent: "Plan Actual", planUpgrade: "Mejorar", planContactUs: "Comprar",
  usesPerDay: "usos / día", wordsPerUse: "palabras / uso", perDay: "/ día", perWeek: "/ semana", perMonth: "/ mes",
  navShareSupport: "Compartir y Soporte", navShare: "Compartir", navFeedback: "Comentarios",
  shareTitle: "Comparte y Gana", shareSubtitle: "Comparte tu enlace de referido con amigos. Cuando se registren, ¡obtienes +3 usos extra!",
  shareLink: "Tu Enlace de Referido", shareLinkDesc: "Comparte este enlace con amigos para ganar usos extra",
  shareQrCode: "Código QR", shareCopied: "¡Copiado!", shareCopyLink: "Copiar Enlace",
  shareBonus: "Bono de Referido", shareBonusDesc: "Ganarás +3 usos gratis cuando un nuevo usuario se registre con tu enlace (bono único)",
  feedbackTitle: "Comentarios", feedbackSubtitle: "¡Ayúdanos a mejorar! Comparte tus ideas o sugerencias (máx. 100 caracteres)",
  feedbackPlaceholder: "Cuéntanos qué piensas...", feedbackSubmit: "Enviar", feedbackSubmitting: "Enviando...",
  feedbackSuccess: "¡Gracias por tus comentarios!", feedbackError: "Error al enviar, intenta de nuevo", feedbackCharCount: "caracteres",
  navBusiness: "Negocios", navCooperation: "Cooperación",
  cooperationTitle: "Cooperación Comercial", cooperationSubtitle: "¿Interesado en asociarte con nosotros? ¡Contáctanos!",
  cooperationEmail: "Email de Contacto", cooperationDesc: "Para consultas comerciales, asociaciones u oportunidades de colaboración, contáctanos por email.",
  turnitinDisclaimer: "Esta es una puntuación estimada. Para resultados oficiales, utilice Turnitin directamente.",
};

const ar: Translations = {
  siteTitle: "HumanizeAI - إنسنة النصوص الذكية", siteDescription: "حوّل المقالات المولدة بالذكاء الاصطناعي إلى أسلوب كتابة بشري طبيعي، لتقليل معدل كشف Turnitin",
  brand: "HumanizeAI", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج",
  heroTitle1: "اجعل نص الذكاء الاصطناعي", heroTitle2: " بشرياً مجدداً ",
  heroSubtitle: "حوّل المقالات المولدة بواسطة ChatGPT و DeepSeek وأدوات الذكاء الاصطناعي الأخرى إلى أسلوب كتابة بشري طبيعي وسلس. قلّل معدل كشف Turnitin إلى أقل من 19%.",
  heroCta: "ابدأ مجاناً",
  featureSmartTitle: "إعادة كتابة ذكية", featureSmartDesc: "مدعوم بـ GPT-4o مع ثلاث مستويات كثافة، مع الحفاظ الدقيق على المعنى الأكاديمي",
  featureLowAiTitle: "كشف AI منخفض", featureLowAiDesc: "محسّن لـ Turnitin — وضع إعادة الكتابة العميق يمكنه تحقيق أقل من 19%",
  featureFastTitle: "سريع وسهل", featureFastDesc: "الصق النص وأعد الكتابة بنقرة واحدة، استخدامات مجانية يومياً",
  editorTitle: "إعادة كتابة النص", editorSubtitle: "الصق النص المولد بالذكاء الاصطناعي، اختر كثافة إعادة الكتابة، واحصل على نتائج بشرية بنقرة واحدة",
  todayRemaining: "المتبقي اليوم:", rewriting: "جاري إعادة الكتابة...", startRewrite: "ابدأ إعادة الكتابة",
  modeLight: "خفيف", modeLightDesc: "تغييرات طفيفة، استبدال المفردات النموذجية للذكاء الاصطناعي",
  modeMedium: "متوسط", modeMediumDesc: "إعادة هيكلة الجمل، تعديل التعبيرات",
  modeDeep: "عميق", modeDeepDesc: "إعادة كتابة كاملة، مع الحفاظ على المعنى الأصلي",
  originalText: "النص الأصلي", words: "كلمة", paste: "لصق", clear: "مسح",
  editorPlaceholder: "الصق نص المقال المولد بالذكاء الاصطناعي هنا...\n\nيدعم النصوص من ChatGPT و DeepSeek و Claude وأدوات AI الأخرى.\nموصى به: لا يزيد عن 2,000 كلمة لكل إرسال.",
  rewriteResult: "نتيجة إعادة الكتابة", copy: "نسخ",
  loadingPlaceholder: "جاري إعادة الكتابة، يرجى الانتظار...",
  resultPlaceholder: "سيظهر النص المعاد كتابته هنا...",
  aiRewriting: "الذكاء الاصطناعي يعيد كتابة نصك...",
  toastNoText: "يرجى إدخال نص لإعادة الكتابة أولاً",
  toastTooLong: "النص يتجاوز حد 2,000 كلمة، يرجى التقسيم والإرسال",
  toastTooShort: "النص قصير جداً، يرجى إدخال 10 كلمات على الأقل",
  toastFailed: "فشلت إعادة الكتابة", toastSuccess: "اكتملت إعادة الكتابة!",
  toastNetworkError: "خطأ في الشبكة، يرجى المحاولة لاحقاً",
  loginTitle: "تسجيل الدخول إلى HumanizeAI", loginDesc: "سجّل الدخول بحساب Google الخاص بك لبدء استخدام إعادة كتابة النصوص بالذكاء الاصطناعي",
  loginGoogle: "تسجيل الدخول بـ Google", loginTerms: "بتسجيل الدخول، فإنك توافق على شروط الخدمة وسياسة الخصوصية",
  loading: "جاري التحميل...",
  aiDetect: "كشف AI", detecting: "جاري الكشف...",
  estimatedAiRate: "معدل AI المقدر", aiRateLabel: "معدل كشف AI",
  vocabulary: "المفردات", structure: "بنية الجمل", flow: "تدفق الفقرات", voice: "الصوت البشري",
  aiRatePass: "ناجح — أقل من عتبة Turnitin", aiRateWarning: "حدودي — فكر في إعادة الكتابة العميقة",
  aiRateFail: "خطر عالي — استخدم وضع إعادة الكتابة العميق",
  dashboard: "لوحة التحكم", dashboardTitle: "لوحة التحكم", dashboardSubtitle: "اعرض استخدامك وأحدث نتائج كشف الذكاء الاصطناعي",
  todayUsage: "استخدام اليوم", lastResult: "أحدث نتيجة إعادة كتابة",
  noResultYet: "لا توجد نتائج بعد", noResultDesc: "أكمل إعادة كتابة لمشاهدة تحليل كشف AI هنا",
  goRewrite: "اذهب لإعادة الكتابة", overallAiRate: "معدل AI الإجمالي", detailBreakdown: "التفاصيل",
  navTools: "أدوات", navAiRewrite: "إعادة الكتابة AI", navAiDetect: "كشف AI",
  navAccount: "الحساب", navProfile: "الملف الشخصي", navPlans: "الخطط والأسعار",
  detectTitle: "كشف AI", detectSubtitle: "الصق أي نص للتحقق من معدل كشف AI",
  detectPlaceholder: "الصق النص هنا لتحليل معدل كشف AI...\n\nيدعم أي نص أكاديمي إنجليزي.",
  detectButton: "بدء الكشف", detectResult: "نتيجة الكشف",
  profileTitle: "الملف الشخصي", profileSubtitle: "إدارة معلومات حسابك",
  accountName: "الاسم", accountEmail: "البريد الإلكتروني", accountPlan: "الخطة الحالية",
  planFree: "مجاني", planPro: "احترافي",
  plansTitle: "الخطط والأسعار", plansSubtitle: "اختر الخطة المناسبة لاحتياجاتك",
  planFreeTitle: "مجاني", planFreeDesc: "ابدأ بالوصول الأساسي",
  planDayTitle: "يومي", planDayDesc: "وصول كامل لمدة 24 ساعة", planDayPrice: "$0.99",
  planWeekTitle: "أسبوعي", planWeekDesc: "وصول كامل لمدة 7 أيام", planWeekPrice: "$3.99",
  planProTitle: "احترافي", planProDesc: "افتح كل الإمكانيات للكتابة الأكاديمية",
  planFreePrice: "$0", planProPrice: "$14.99",
  planCurrent: "الخطة الحالية", planUpgrade: "ترقية", planContactUs: "اشتر الآن",
  usesPerDay: "استخدام / يوم", wordsPerUse: "كلمة / استخدام", perDay: "/ يوم", perWeek: "/ أسبوع", perMonth: "/ شهر",
  navShareSupport: "المشاركة والدعم", navShare: "مشاركة", navFeedback: "ملاحظات",
  shareTitle: "شارك واكسب", shareSubtitle: "شارك رابط الإحالة مع أصدقائك. عندما يسجلون، تحصل على +3 استخدامات إضافية!",
  shareLink: "رابط الإحالة الخاص بك", shareLinkDesc: "شارك هذا الرابط مع أصدقائك لكسب استخدامات إضافية",
  shareQrCode: "رمز QR", shareCopied: "تم النسخ!", shareCopyLink: "نسخ الرابط",
  shareBonus: "مكافأة الإحالة", shareBonusDesc: "ستحصل على +3 استخدامات مجانية عند تسجيل مستخدم جديد عبر رابطك (مكافأة لمرة واحدة)",
  feedbackTitle: "ملاحظات", feedbackSubtitle: "ساعدنا على التحسين! شارك أفكارك أو اقتراحاتك (حد أقصى 100 حرف)",
  feedbackPlaceholder: "أخبرنا برأيك...", feedbackSubmit: "إرسال", feedbackSubmitting: "جاري الإرسال...",
  feedbackSuccess: "شكراً لملاحظاتك!", feedbackError: "فشل الإرسال، حاول مرة أخرى", feedbackCharCount: "حرف",
  navBusiness: "أعمال", navCooperation: "تعاون",
  cooperationTitle: "التعاون التجاري", cooperationSubtitle: "مهتم بالشراكة معنا؟ تواصل معنا!",
  cooperationEmail: "البريد الإلكتروني للتواصل", cooperationDesc: "للاستفسارات التجارية أو الشراكات أو فرص التعاون، يرجى التواصل معنا عبر البريد الإلكتروني.",
  turnitinDisclaimer: "هذه نتيجة تقديرية. للحصول على النتائج الرسمية، يرجى استخدام Turnitin مباشرة.",
};

const translations: Record<Locale, Translations> = { en, "zh-CN": zhCN, "zh-TW": zhTW, es, ar };

interface I18nContextType { locale: Locale; t: Translations; setLocale: (locale: Locale) => void; }
const I18nContext = createContext<I18nContextType | null>(null);
const RTL_LOCALES: Locale[] = ["ar"];

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");
  useEffect(() => {
    const saved = localStorage.getItem("locale") as Locale | null;
    if (saved && LOCALES.includes(saved)) setLocaleState(saved);
  }, []);
  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = RTL_LOCALES.includes(locale) ? "rtl" : "ltr";
  }, [locale]);
  const setLocale = useCallback((l: Locale) => { setLocaleState(l); localStorage.setItem("locale", l); }, []);
  const t = translations[locale];
  return <I18nContext.Provider value={{ locale, t, setLocale }}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error("useI18n must be used within I18nProvider");
  return ctx;
}
